branches:
  only:
  - master
  - development
  - "/^release-.*$/"
language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-28
before_install:
- openssl aes-256-cbc -K $encrypted_9498d2163fe1_key -iv $encrypted_9498d2163fe1_iv
  -in ./keystore.jks.enc -out ./keystore.jks -d
- openssl aes-256-cbc -K $encrypted_22c643d0471b_key -iv $encrypted_22c643d0471b_iv
  -in ./sampleApp/google-services.json.enc -out ./sampleApp/google-services.json -d
- yes | sdkmanager "platforms;android-28"
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
before_script: 
script:
- "./gradlew clean build testDebugUnitTest"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
deploy:
  skip_cleanup: true
  provider: script
  script: "./gradlew clean install bintrayUpload"
  on:
    branch: master
after_failure: cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml